[tool.black]
line-length = 88
skip-string-normalization = false
skip-magic-trailing-comma = false
exclude = '''
(\n  /(
    \.git
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''
docstring-style = "preserve"
